services:
  - type: web
    name: vibron-socket
    runtime: node
    plan: starter # Use 'free' for testing, 'starter' for production
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: ts-node index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: vibron-redis
          property: connectionString
    domains:
      - socket.vibronmax.com
  - type: keyvalue
    name: vibron-redis
    plan: free # Use 'free' for testing, 'starter' for production
    ipAllowList: [] # Restrict to internal connections